# â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
# â”‚  General Formatting â”‚
# â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

format = """
[â•­â•´](fg:#5b6078)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$fill\
$python\
$nodejs\
$deno\
$c\
$rust\
$golang\
$docker_context\
$elixir\
$java\
$kotlin\
$scala\
$haskell\
$nim\
$gradle\
$elm\
$julia\
$lua\
$erlang\
$gleam\
$ocaml\
$purescript\
$typst\
$pulumi\
$nix_shell\
$direnv\
$aws\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = true
palette = "catppuccin_macchiato"

# â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
# â”‚  Palettes    â”‚
# â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo  = "#f0c6c6"
pink      = "#f5bde6"
mauve     = "#c6a0f6"
red       = "#ed8796"
maroon    = "#ee99a0"
peach     = "#f5a97f"
yellow    = "#eed49f"
green     = "#a6da95"
teal      = "#8bd5ca"
sky       = "#91d7e3"
sapphire  = "#7dc4e4"
blue      = "#8aadf4"
lavender  = "#b7bdf8"
text      = "#cad3f5"
subtext0  = "#a5adcb"
overlay1  = "#8087a2"
surface2  = "#5b6078"
surface1  = "#494d64"
surface0  = "#363a4f"
base      = "#24273a"
mantle    = "#1e2030"
crust     = "#181926"

# â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
# â”‚  Modules     â”‚
# â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

[fill]
style = 'fg:#5b6078'
symbol = "\u2500"

[character]
success_symbol = '[Î»](bold fg:flamingo)[Î»](bold fg:sapphire)[Î»](bold fg:green)[Î»](bold fg:peach)[Î»](bold fg:mauve)'
error_symbol   = '[Î»](bold fg:flamingo)[Î»](bold fg:sapphire)[Î»](bold fg:green)[Î»](bold fg:peach)[Î»](bold fg:mauve)'

[username]
show_always = false
style_user = "bg:peach fg:base"
style_root = "bg:peach fg:base"
format = '[ ï€‡ $user ]($style)'
disabled = false

[hostname]
ssh_only = true
style = "bg:peach fg:base"
format = "[ ï‘­ $hostname ]($style)"

[directory]
style = "bg:mauve fg:base"
format = "[ ï¼ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
fish_style_pwd_dir_length = 1

[git_branch]
symbol = "ï˜"
style = "bg:blue fg:base"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:blue fg:base"
format = '([ îœ§ $all_status$ahead_behind ]($style))'

[cmd_duration]
min_time = 500
style = "bg:lavender fg:base"
format = "[ ï‰’ $duration ]($style)"

[time]
disabled = false
style = "bg:mantle fg:text"
format = "[ ïº $time ]($style)"
time_format = "%H:%M"

# â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
# â”‚  Programming Languages  â”‚
# â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

[c]
symbol = "î˜"
style = "bg:red fg:base"
format = "[ $symbol ($version) ]($style)"

[elixir]
symbol = "î‰µ"
style = "bg:maroon fg:base"
format = "[ $symbol ($version) ]($style)"

[elm]
symbol = "î˜¬"
style = "bg:peach fg:base"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = "î˜§"
style = "bg:teal fg:base"
format = "[ $symbol ($version) ]($style)"

[gradle]
symbol = "î™ "
style = "bg:green fg:base"
format = "[ $symbol ($version) ]($style)"

[haskell]
symbol = "î·"
style = "bg:lavender fg:base"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = "î‰–"
style = "bg:yellow fg:base"
format = "[ $symbol ($version) ]($style)"

[julia]
symbol = "î˜¤"
style = "bg:sky fg:base"
format = "[ $symbol ($version) ]($style)"

[kotlin]
symbol = "î˜´"
style = "bg:mauve fg:base"
format = "[ $symbol ($version) ]($style)"

[nim]
symbol = "ó°†¥"
style = "bg:yellow fg:base"
format = "[ $symbol ($version) ]($style)"

[nix_shell]
symbol = "ïŒ“"
style = "bg:blue fg:base"
format = "[ $symbol $state ]($style)"

[nodejs]
symbol = "îœ˜"
style = "bg:green fg:base"
format = "[ $symbol ($version) ]($style)"

[deno]
symbol = "î¨"
style = "bg:green fg:base"
format = "[ $symbol ($version) ]($style)"

[perl]
symbol = "î©"
style = "bg:pink fg:base"
format = "[ $symbol ($version) ]($style)"

[php]
symbol = "î˜ˆ"
style = "bg:flamingo fg:base"
format = "[ $symbol ($version) ]($style)"

[python]
symbol = "îœ¼"
style = "bg:green fg:base"
format = "[ $symbol ($version) ]($style)"

[ruby]
symbol = "î‘"
style = "bg:red fg:base"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = "î¨"
style = "bg:red fg:base"
format = "[ $symbol ($version) ]($style)"

[scala]
symbol = "îœ·"
style = "bg:maroon fg:base"
format = "[ $symbol ($version) ]($style)"

[swift]
symbol = "î•"
style = "bg:peach fg:base"
format = "[ $symbol ($version) ]($style)"

[zig]
symbol = "îš©"
style = "bg:yellow fg:base"
format = "[ $symbol ($version) ]($style)"

[lua]
symbol = "î˜ "
style = "bg:blue fg:base"
format = "[ $symbol ($version) ]($style)"

[erlang]
symbol = "î±"
style = "bg:red fg:base"
format = "[ $symbol ($version) ]($style)"

[gleam]
symbol = "ó±˜–"
style = "bg:lavender fg:base"
format = "[ $symbol ($version) ]($style)"

[ocaml]
symbol = "î™º"
style = "bg:mauve fg:base"
format = "[ $symbol ($version) ]($style)"

[purescript]
symbol = "î˜°"
style = "bg:sky fg:base"
format = "[ $symbol ($version) ]($style)"

[typst]
symbol = "ó±˜"
style = "bg:blue fg:base"
format = "[ $symbol ($version) ]($style)"

# â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
# â”‚   Tooling    â”‚
# â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜

[docker_context]
symbol = "ïŒˆ"
style = "bg:sapphire fg:base"
format = "[ $symbol $context ]($style)"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = 'ğŸ…° '

[direnv]
symbol = "ó°’“"
style = "bg:sky fg:base"
format = "[ $symbol ]($style)"

[terraform]
symbol = "ó°¡¼"
style = "bg:maroon fg:base"
format = "[ $symbol ($version) ]($style)"

[pulumi]
symbol = "ó±„¨"
style = "bg:flamingo fg:base"
format = "[ $symbol ($version) ]($style)"
